import { KeyRound, Save, ShieldCheck, UserRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import { api } from '../api/client';
import Toast from '../components/Toast';
import { useAuth } from '../context/AuthContext';

export default function ProfilePage() {
  const { user, setUser } = useAuth();
  const [form, setForm] = useState(user); const [password, setPassword] = useState({ currentPassword: '', newPassword: '' }); const [toast, setToast] = useState(null); const [error, setError] = useState('');
  useEffect(() => setForm(user), [user]);
  const save = async (event) => { event.preventDefault(); try { const data = await api('/users/profile', { method: 'PATCH', body: form }); setUser(data.user); setToast({ message: data.message }); } catch (err) { setError(err.message); } };
  const changePassword = async (event) => { event.preventDefault(); try { const data = await api('/auth/change-password', { method: 'PATCH', body: password }); setPassword({ currentPassword: '', newPassword: '' }); setToast({ message: data.message }); } catch (err) { setError(err.message); } };
  return <div className="profile-page"><Toast toast={toast} onClose={() => setToast(null)} /><div className="page-intro"><div><h2>Profile & security</h2><p>Keep your personal and ministry details up to date.</p></div></div>{error && <div className="form-error">{error}</div>}
    <div className="profile-grid"><aside className="panel profile-summary"><span className="avatar avatar--large" style={{ background: form.avatarColor }}>{form.firstName[0]}{form.lastName[0]}</span><h3>{form.firstName} {form.lastName}</h3><p>{form.role === 'pastor' ? 'Pastor administrator' : form.ministry || 'Church leader'}</p><span className="verified"><ShieldCheck size={15} /> Secure account</span><small>Member since {new Date(form.createdAt).toLocaleDateString(undefined, { month: 'long', year: 'numeric' })}</small><div className="color-picker"><label>Profile colour</label>{['#315d56','#876a32','#78506b','#345b78','#6d4938'].map((color) => <button key={color} type="button" className={form.avatarColor === color ? 'selected' : ''} style={{ background: color }} onClick={() => setForm({ ...form, avatarColor: color })} />)}</div></aside>
      <main><form className="panel settings-form" onSubmit={save}><header><UserRound /><div><h3>Personal information</h3><p>This information is visible to the pastor inside your reports.</p></div></header><div className="form-row"><label>First name<input required value={form.firstName} onChange={(e) => setForm({ ...form, firstName: e.target.value })} /></label><label>Last name<input required value={form.lastName} onChange={(e) => setForm({ ...form, lastName: e.target.value })} /></label></div><label>Email address<input value={form.email} disabled /><small>Email addresses are unique and cannot be changed here.</small></label><div className="form-row"><label>Phone number<input value={form.phone || ''} onChange={(e) => setForm({ ...form, phone: e.target.value })} placeholder="Optional" /></label><label>Ministry / leadership role<input value={form.ministry || ''} onChange={(e) => setForm({ ...form, ministry: e.target.value })} placeholder="e.g. Youth ministry" /></label></div><label>Short bio<textarea rows="3" maxLength="500" value={form.bio || ''} onChange={(e) => setForm({ ...form, bio: e.target.value })} placeholder="A little about your leadership role" /></label><div className="form-footer"><button className="button button--primary button--small"><Save size={16} /> Save profile</button></div></form>
      <form className="panel settings-form" onSubmit={changePassword}><header><KeyRound /><div><h3>Change password</h3><p>Use at least 8 characters and keep your password private.</p></div></header><div className="form-row"><label>Current password<input type="password" required value={password.currentPassword} onChange={(e) => setPassword({ ...password, currentPassword: e.target.value })} /></label><label>New password<input type="password" required minLength="8" value={password.newPassword} onChange={(e) => setPassword({ ...password, newPassword: e.target.value })} /></label></div><div className="form-footer"><button className="button button--ghost button--small">Update password</button></div></form></main>
    </div>
  </div>;
}
