import { ArrowLeft, CalendarDays, Check, Edit3, FileLock2, LockKeyhole, MessageCircle, Save, Send, UserRound, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useLocation, useParams } from 'react-router-dom';
import { api } from '../api/client';
import StatusBadge, { statusLabels } from '../components/StatusBadge';
import Toast from '../components/Toast';
import { useAuth } from '../context/AuthContext';

export default function ReportDetailPage() {
  const { id } = useParams(); const location = useLocation(); const { user } = useAuth(); const pastor = user.role === 'pastor';
  const [report, setReport] = useState(null); const [message, setMessage] = useState(''); const [edit, setEdit] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); const [toast, setToast] = useState(location.state?.toast ? { message: location.state.toast } : null);
  useEffect(() => { api(`/reports/${id}`).then((data) => setReport(data.report)).catch((err) => setError(err.message)); }, [id]);
  const respond = async (event) => { event.preventDefault(); if (!message.trim()) return; setLoading(true); try { const data = await api(`/reports/${id}/responses`, { method: 'POST', body: { message } }); setReport(data.report); setMessage(''); setToast({ message: data.message }); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  const status = async (value) => { try { const data = await api(`/reports/${id}/status`, { method: 'PATCH', body: { status: value } }); setReport((current) => ({ ...current, ...data.report })); setToast({ message: data.message }); } catch (err) { setError(err.message); } };
  const saveEdit = async () => { setLoading(true); try { const data = await api(`/reports/${id}`, { method: 'PATCH', body: edit }); setReport((current) => ({ ...current, ...data.report })); setEdit(null); setToast({ message: data.message }); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  if (error && !report) return <div className="form-error">{error} <Link to="/app/reports">Return to reports</Link></div>;
  if (!report) return <div className="panel-loading full-height"><span className="spinner" /></div>;
  return <div className="report-detail-page">
    <Toast toast={toast} onClose={() => setToast(null)} />
    <div className="page-intro report-detail-header"><div><Link to="/app/reports"><ArrowLeft size={15} /> Back to reports</Link><div className="detail-title"><span className={`report-icon report-icon--${report.sensitivity}`}><FileLock2 /></span><div><div><span>{report.reference}</span><StatusBadge status={report.status} /></div><h2>{report.title}</h2></div></div></div><div className="detail-actions">{!pastor && report.status !== 'closed' && <button className="button button--ghost button--small" onClick={() => setEdit({ title: report.title, content: report.content, category: report.category, urgency: report.urgency, sensitivity: report.sensitivity })}><Edit3 size={16} /> Edit report</button>}{pastor && <label className="status-select">Status<select value={report.status} onChange={(e) => status(e.target.value)}>{Object.entries(statusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>}</div></div>
    {error && <div className="form-error">{error}</div>}
    <div className="detail-grid"><main>
      <section className="panel original-report"><header><div><span className="avatar" style={{ background: report.owner.avatarColor }}>{report.owner.firstName[0]}{report.owner.lastName[0]}</span><div><strong>{report.owner.firstName} {report.owner.lastName}</strong><small>Original report · {new Date(report.createdAt).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' })}</small></div></div><span className="privacy-pill"><LockKeyhole size={13} /> Confidential</span></header>
        {edit ? <div className="edit-report"><label>Subject<input value={edit.title} onChange={(e) => setEdit({ ...edit, title: e.target.value })} /></label><label>Message<textarea rows="9" value={edit.content} onChange={(e) => setEdit({ ...edit, content: e.target.value })} /></label><div><button className="button button--ghost button--small" onClick={() => setEdit(null)}><X size={15} /> Cancel</button><button className="button button--primary button--small" onClick={saveEdit} disabled={loading}><Save size={15} /> Save changes</button></div></div> : <div className="original-report__content"><p>{report.content}</p><div className="report-tags"><span>{report.category}</span><span className={`urgency urgency--${report.urgency}`}>{report.urgency}</span>{report.sensitivity === 'private' && <span>Highly sensitive</span>}</div></div>}
      </section>
      <div className="conversation-label"><span>Private conversation</span></div>
      <section className="conversation">{report.responses.length === 0 ? <div className="conversation-empty"><MessageCircle /><h3>No responses yet</h3><p>{pastor ? 'Send a thoughtful response to begin this pastoral conversation.' : 'Your pastor will respond here after reviewing your report.'}</p></div> : report.responses.map((response) => { const mine = String(response.author?._id || response.author) === user.id; return <article className={`message ${mine ? 'message--mine' : ''}`} key={response._id}><span className="avatar avatar--small" style={{ background: response.author?.avatarColor || '#315d56' }}>{response.author?.firstName?.[0]}{response.author?.lastName?.[0]}</span><div><header><strong>{mine ? 'You' : `${response.author?.firstName || ''} ${response.author?.lastName || ''}`}</strong><small>{response.authorRole === 'pastor' ? 'Pastor' : 'Church leader'} · {new Date(response.createdAt).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' })}</small></header><p>{response.message}</p>{mine && <i><Check size={13} /> Sent privately</i>}</div></article>; })}</section>
      {report.status !== 'closed' ? <form className="reply-box" onSubmit={respond}><label>{pastor ? `Respond privately to ${report.owner.firstName}` : 'Reply to your pastor'}<textarea rows="4" value={message} onChange={(e) => setMessage(e.target.value)} placeholder="Write a thoughtful response..." /></label><div><span><LockKeyhole size={14} /> Only this conversation’s participants can read it</span><button className="button button--primary button--small" disabled={loading || !message.trim()}><Send size={15} /> Send response</button></div></form> : <div className="closed-note"><LockKeyhole /> This matter has been closed. The conversation remains available to read.</div>}
    </main><aside className="report-aside">
      <section className="panel"><h3>Report details</h3><dl><div><dt><CalendarDays />Submitted</dt><dd>{new Date(report.createdAt).toLocaleDateString(undefined, { dateStyle: 'medium' })}</dd></div><div><dt><FileLock2 />Sensitivity</dt><dd>{report.sensitivity === 'private' ? 'Highly sensitive' : 'Confidential'}</dd></div><div><dt><MessageCircle />Responses</dt><dd>{report.responses.length}</dd></div></dl></section>
      {pastor && <section className="panel leader-card"><h3>Submitted by</h3><span className="avatar" style={{ background: report.owner.avatarColor }}>{report.owner.firstName[0]}{report.owner.lastName[0]}</span><strong>{report.owner.firstName} {report.owner.lastName}</strong><small>{report.owner.ministry || 'Church leader'}</small><a href={`mailto:${report.owner.email}`}>{report.owner.email}</a>{report.owner.phone && <p>{report.owner.phone}</p>}<div><UserRound size={15} /> Account details are pastor-only</div></section>}
    </aside></div>
  </div>;
}
